# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import normalized_filefield.model_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254)),
                ('required_text', models.CharField(max_length=254)),
                ('required_file', normalized_filefield.model_field.NormalizedFileField(upload_to='media/uploads/required')),
                ('optional_text', models.CharField(blank=True, max_length=254, null=True)),
                ('optional_file', normalized_filefield.model_field.NormalizedFileField(blank=True, null=True, upload_to='media/uploads/optional')),
            ],
        ),
    ]
